### ISSUE TITLE
[plugin.video.skyticket.de] does  not play streams anymore

### ISSUE THREAD

**Issue by jboeddeker** [kodinerds/repo#110]
I can't play streams with skyticket addon since 2019-07-01. Worked flawlessy before. Browsing through skyticket works.

I am running skyticket on latest OSMC, Vero4K and RaspberryPi 3. Result is the same on both hardware.

Netflix & Amazon, which also use the widevine stuff, still work.

Thanks for any help!

```
019-07-06 10:01:02.381 T:4068491264   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
2019-07-06 10:01:18.422 T:3926909664   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: No JSON object could be decoded
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.skyticket.de/default.py", line 41, in <module>
                                                liveTv.playLiveTv(params['manifest_url'], package_code=params.get('package_code'), infolabels=getDictFromString(params.get('infolabels', None)), art=getDictFromString(params.get('art', None)), parental_rating=int(params.get('parental_rating', 0)))
                                              File "/home/osmc/.kodi/addons/plugin.video.skyticket.de/resources/lib/liveTv.py", line 30, in playLiveTv
                                                skyticket.play(manifest_url, package_code, parental_rating=parental_rating, info_tag=infolabels, art_tag=art, apix_id=apix_id)
                                              File "/home/osmc/.kodi/addons/plugin.video.skyticket.de/skyticket.py", line 316, in play
                                                if self.login(username, password):
                                              File "/home/osmc/.kodi/addons/plugin.video.skyticket.de/skyticket.py", line 130, in login
                                                if forceLogin or not self.isLoggedIn():
                                              File "/home/osmc/.kodi/addons/plugin.video.skyticket.de/skyticket.py", line 95, in isLoggedIn
                                                response = json.loads(response)
                                              File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
                                                return _default_decoder.decode(s)
                                              File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
                                                obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                              File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
                                                raise ValueError("No JSON object could be decoded")
                                            ValueError: No JSON object could be decoded
                                            -->End of Python script error report<--
2019-07-06 10:01:18.770 T:4068491264   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.skyticket.de/?action=playLive&manifest_url=http%3A%2F%2Fwelt1mssskyde.akamaized.net%2F211413%2Fstream.isml%2FManifest&package_code=OOSW]
```

**Comment by jboeddeker** [comment]
Great job Sky. 

it works again, without changing anything, so the problem was Sky itself.

Sorry.
