### ISSUE TITLE
PythonToCppException in plugin.video.7tv

### ISSUE THREAD

**Issue by odious** [kodinerds/repo#13]
Hey there, 

i am currently running Kodi 16 and getting the following error when using the 7TV-plugin:

`12:58:22 T:1681781664  NOTICE: [plugin.video.7tv] Running: 7TV (3.1.7) on J..... (16.1) with Python (2.7.12)
12:59:23 T:1949020160  NOTICE: Previous line repeats 2 times.
12:59:23 T:1949020160  NOTICE: DVDPlayer: Opening: http://vod-level3-psd-progressive.p7s1digital.de/clips/09/69/2343851-1gu9x2r-tp08.mp4?token=00~23c3ab~23c3ab~581f1b1a
~15180~0-bb113c808011232d29bb25241&ts=1478433562&access_token=hbbtv&video=2328000&bp=AAH6g4d0dZQXOa3S_qzkl4RYgFNtNfzfUsNvSQbQrw
12:59:23 T:1949020160 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
12:59:23 T:1681781664  NOTICE: Creating InputStream
12:59:24 T:1681781664  NOTICE: Creating Demuxer
12:59:44 T:1681781664   ERROR: Open - Error, could not open file http://vod-level3-psd-progressive.p7s1digital.de/clips/09/69/2343851-1gu9x2r-tp08.mp4?token=00~23c3ab~2
3c3ab~581f1b1a~15180~0-bb113c808011232d29bb25241&ts=1478433562&access_token=hbbtv&video=2328000&bp=AAH6g4d0dZQXOa3S_qzkl4RYgFNtNfzfUsNvSQbQrw
12:59:44 T:1681781664   ERROR: OpenDemuxStream - Error creating demuxer
12:59:44 T:1681781664  NOTICE: CDVDPlayer::OnExit()
13:00:37 T:1949020160   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.7tv/play/?video_id=2343851]
13:00:37 T:1949020160  NOTICE: CDVDPlayer::CloseFile()
`

When I try to open the URL with my browser (Chromium), it works fine.

Also, sometimes the following error occurs, which seems to be related:

`13:05:53 T:1857024928  NOTICE: [plugin.video.7tv] Running: 7TV (3.1.7) on J..... (16.1) with Python (2.7.12)
13:06:25 T:1857024928   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.URLError'>
                                            Error Contents: <urlopen error [Errno -2] Name or service not known>
                                            Traceback (most recent call last):
                                              File "/var/lib/kodi/.kodi/addons/plugin.video.7tv/addon.py", line 6, in <module>
                                                nightcrawler.run(content.Provider())
                                              File "/var/lib/kodi/.kodi/addons/plugin.video.7tv/resources/lib/nightcrawler/core/runner.py", line 47, in run
                                                result = provider.navigate(context)
                                              File "/var/lib/kodi/.kodi/addons/plugin.video.7tv/resources/lib/nightcrawler/provider.py", line 174, in navigate
                                                result = method(context)
                                              File "/var/lib/kodi/.kodi/addons/plugin.video.7tv/resources/lib/nightcrawler/core/nightcrawler_decorators.py", line 44, in wrapper
                                                return func(*args, **kwargs)
                                              File "/var/lib/kodi/.kodi/addons/plugin.video.7tv/resources/lib/nightcrawler/core/nightcrawler_decorators.py", line 126, in wrapper
                                                return func(*args, **kwargs)
                                              File "/var/lib/kodi/.kodi/addons/plugin.video.7tv/resources/lib/content/provider.py", line 236, in play
                                                video_streams = self._get_client(context).get_video_url(video_id)
                                              File "/var/lib/kodi/.kodi/addons/plugin.video.7tv/resources/lib/content/client.py", line 239, in get_video_url
                                                videos = self._get_video_url(video_id, access_token, access_token, client_location, salt, source_id)
                                              File "/var/lib/kodi/.kodi/addons/plugin.video.7tv/resources/lib/content/client.py", line 316, in _get_video_url
                                                json_data = self._request(json_url, headers={'Accept-Encoding': 'gzip'})
                                              File "/var/lib/kodi/.kodi/addons/plugin.video.7tv/resources/lib/content/client.py", line 38, in _request
                                                response = super(Client, self)._request(url, method, self._default_header, post_data, params, allow_redirects)
                                              File "/var/lib/kodi/.kodi/addons/plugin.video.7tv/resources/lib/nightcrawler/http/client.py", line 31, in _request
                                                result = get(url, params=params, headers=_headers, verify=self._verify, allow_redirects=allow_redirects)
                                              File "/var/lib/kodi/.kodi/addons/plugin.video.7tv/resources/lib/nightcrawler/http/api.py", line 215, in get
                                                return _request('GET', url, **kwargs)
                                              File "/var/lib/kodi/.kodi/addons/plugin.video.7tv/resources/lib/nightcrawler/http/api.py", line 189, in _request
                                                response = opener.open(request)
                                              File "/usr/lib/python2.7/urllib2.py", line 429, in open
                                                response = self._open(req, data)
                                              File "/usr/lib/python2.7/urllib2.py", line 447, in _open
                                                '_open', req)
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                                result = func(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
                                                return self.do_open(httplib.HTTPConnection, req)
                                              File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
                                                raise URLError(err)
                                            URLError: <urlopen error [Errno -2] Name or service not known>
                                            -->End of Python script error report<--
13:06:25 T:1949020160   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.7tv/play/?video_id=2343851]
`

**Comment by tyl0re** [comment]
What 7tv have you installed 7tv or 7tv iputstrea?

**Comment by unidesign** [comment]
Both the first and second error reports are related to `plugin://plugin.video.7tv/play/?video_id=2343851`.
The first report shows that you're in fact able to get the stream url for the same video few minutes before.
I never got such an error, but I would say either your network is not stable or their server is not stable or they have blocked you/your kodi session (cookie) because of massive video consumption.
To be honest I have to say although I developed the video url function I never really used/tested this addon deeper.

**Comment by odious** [comment]
@tyl0re 
I am using 7tv 3.1.7

@unidesign 
Thanks for the input, so there is no real way to "fix" this, I guess? Massive consumption does sound unreasonable, we watch like 1-2 Episodes per evening.

**Comment by unidesign** [comment]
@odious 
In your specific case I would do the following: Enable `Always ask for video quality` in the settings.
If a video fails next time just choose another quality and try again. If the other quality succeeds you know it's not your problem, if not try another video if it fails again and other video addons work it's your network. If not it's their problem.

You told that the same mp4 url works in chromium. The only difference there is, that the browser passes the `User-Agent` Header. In the absolute worst case you could give Kodi this header too:
Add `+ '|User-Agent=Mozilla/5.0' ` to url parameter of lines 265 and 283.

But as I said, for me everything works flawless without it.

**Comment by tyl0re** [comment]
Does the Problem still exists, if not i would colose this issue

**Comment by odious** [comment]
Yeah the Problem is gone. 
For anyone with related issues: it was routing/wlan related. My Raspberry Pi was connected both via LAN and WLAN and for some reason prioritized the (unstable) WLAN connection.
