### ISSUE TITLE
DailyMotion add-on not working

### ISSUE THREAD

**Issue by zblue89** [kodinerds/repo#15]
Getting the following error when loading DailyMotion video

```
22:50:26 1384999.875000 T:1425609712  NOTICE: DILYMOTION_Gates - m_url = http://www.dailymotion.com/cdn/manifest/video/x52wp05.m3u8?auth=1480085425-2562-p5xrnv19-ad55fb00e2dacf42eb4e2721e56068d4
22:50:26 1384999.875000 T:1425609712  NOTICE: DILYMOTION_Gates - m_url = http://www.dailymotion.com/cdn/manifest/video/x52wp05.m3u8?auth=1480085425-2562-p5xrnv19-ad55fb00e2dacf42eb4e2721e56068d4&include=720
22:50:26 1385000.500000 T:1425609712   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.dailymotion_com/default.py", line 587, in <module>
                                                playVideo(url)
                                              File "/home/osmc/.kodi/addons/plugin.video.dailymotion_com/default.py", line 248, in playVideo
                                                url = getStreamUrl(id)
                                              File "/home/osmc/.kodi/addons/plugin.video.dailymotion_com/default.py", line 310, in getStreamUrl
                                                return "http://"+match[0]+".m3u8"
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
```

I tried to fix it myself and found that `redirect=0` is required in `m_url`.

Below is my fix:

```
elif  int(source) <= int(maxVideoQuality) : #LINE 306
    # -------- ADDED PART ------------
    if '.m3u8?auth' in m_url:
        splitted_url = m_url.split('?auth=')
        m_url = splitted_url[0] + '?redirect=0&auth=' + urllib.quote(splitted_url[1])
    # -------- END ADDED PART ------------

    rr = requests.get(m_url,cookies=r.cookies.get_dict() ,headers=headers)    	
    inhalt = rr.text.split('#cell')[0]  
    match = re.compile('http://(.+?).m3u8', re.DOTALL).findall(inhalt)
    return "http://"+match[0]+".m3u8"

elif '.mnft' in m_url:
    continue
```

TQ

**Comment by tyl0re** [comment]
Havnt Thank you for the Fix, Hope it has worked
Thnaks allot
