### ISSUE TITLE
Failure when playing URLs with Hebrew characters via Yatse

### ISSUE THREAD

**Issue by syagev** [kodinerds/repo#16]
Not sure if this issue is more related to the [Yatse](http://yatse.tv) remote but when using the Android app in order to play a URL with hebrew characters in it the player fails with a message "script failed".

I'm running version 2.2.3 of the plugin on a legacy 32bit XBMC version running on OpenELEC. Attached is the log:
```
15:59:02 T:2884909888  NOTICE: Thread LanguageInvoker start, auto delete: false
15:59:02 T:2884909888  NOTICE: -->Python Interpreter Initialized<--
15:59:02 T:2884909888  NOTICE: The url is ::
15:59:02 T:2884909888  NOTICE: x5491tm_מטומטמת-עונה-1-פרק-6-hd_tv
15:59:03 T:2884909888   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'simplejson.scanner.JSONDecodeError'>
                                            Error Contents: Expecting value: line 1 column 1 (char 0)
                                            Traceback (most recent call last):
                                              File "/storage/.xbmc/addons/plugin.video.dailymotion_com/default.py", line 587, in <module>
                                                playVideo(url)
                                              File "/storage/.xbmc/addons/plugin.video.dailymotion_com/default.py", line 248, in playVideo
                                                url = getStreamUrl(id)
                                              File "/storage/.xbmc/addons/plugin.video.dailymotion_com/default.py", line 281, in getStreamUrl
                                                content = r.json()
                                              File "/storage/.xbmc/addons/script.module.requests/lib/requests/models.py", line 808, in json
                                                return complexjson.loads(self.text, **kwargs)
                                              File "/storage/.xbmc/addons/script.module.simplejson/lib/simplejson/__init__.py", line 488, in loads
                                                return _default_decoder.decode(s)
                                              File "/storage/.xbmc/addons/script.module.simplejson/lib/simplejson/decoder.py", line 370, in decode
                                                obj, end = self.raw_decode(s)
                                              File "/storage/.xbmc/addons/script.module.simplejson/lib/simplejson/decoder.py", line 389, in raw_decode
                                                return self.scan_once(s, idx=_w(s, idx).end())
                                              File "/storage/.xbmc/addons/script.module.simplejson/lib/simplejson/scanner.py", line 119, in scan_once
                                                return _scan_once(string, idx)
                                              File "/storage/.xbmc/addons/script.module.simplejson/lib/simplejson/scanner.py", line 115, in _scan_once
                                                raise JSONDecodeError(errmsg, string, idx)
                                            JSONDecodeError: Expecting value: line 1 column 1 (char 0)
                                            -->End of Python script error report<--
15:59:46 T:2680126272  NOTICE: ES: Client  from 192.168.1.215 timed out
16:00:06 T:2615794496  NOTICE: AddOnLog: PVR IPTV Simple Client: EPG Loaded.
```

**Comment by tyl0re** [comment]
New Version is Online. Could you try it again (it should also not work, but the it would be easy for my debug)

**Comment by syagev** [comment]
The new version is still named 2.2.3?

**Comment by tyl0re** [comment]
Sorry forget to update versionsnumber. New Versionnumber is now online

**Comment by syagev** [comment]
Same behaviour, like you said.

Updated log:
```
08:14:32 T:2298456896  NOTICE: Previous line repeats 1 times.
08:14:32 T:2298456896  NOTICE: Thread LanguageInvoker start, auto delete: false
08:14:32 T:2298456896  NOTICE: -->Python Interpreter Initialized<--
08:14:33 T:2298456896  NOTICE: The url is ::
08:14:33 T:2298456896  NOTICE: x54cvzf_מטומטמת-עונה-1-פרק-16-hd_tv
08:14:33 T:2298456896   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'simplejson.scanner.JSONDecodeError'>
                                            Error Contents: Expecting value: line 1 column 1 (char 0)
                                            Traceback (most recent call last):
                                              File "/storage/.xbmc/addons/plugin.video.dailymotion_com/default.py", line 587, in <module>
                                                playVideo(url)
                                              File "/storage/.xbmc/addons/plugin.video.dailymotion_com/default.py", line 248, in playVideo
                                                url = getStreamUrl(id)
                                              File "/storage/.xbmc/addons/plugin.video.dailymotion_com/default.py", line 281, in getStreamUrl
                                                content = r.json()
                                              File "/storage/.xbmc/addons/script.module.requests/lib/requests/models.py", line 808, in json
                                                return complexjson.loads(self.text, **kwargs)
                                              File "/storage/.xbmc/addons/script.module.simplejson/lib/simplejson/__init__.py", line 488, in loads
                                                return _default_decoder.decode(s)
                                              File "/storage/.xbmc/addons/script.module.simplejson/lib/simplejson/decoder.py", line 370, in decode
                                                obj, end = self.raw_decode(s)
                                              File "/storage/.xbmc/addons/script.module.simplejson/lib/simplejson/decoder.py", line 389, in raw_decode
                                                return self.scan_once(s, idx=_w(s, idx).end())
                                              File "/storage/.xbmc/addons/script.module.simplejson/lib/simplejson/scanner.py", line 119, in scan_once
                                                return _scan_once(string, idx)
                                              File "/storage/.xbmc/addons/script.module.simplejson/lib/simplejson/scanner.py", line 115, in _scan_once
                                                raise JSONDecodeError(errmsg, string, idx)
                                            JSONDecodeError: Expecting value: line 1 column 1 (char 0)
                                            -->End of Python script error report<--
```

**Comment by tyl0re** [comment]
WHat Settings do you have (Country). or how do i find the Video. So i can test it ?

**Comment by tyl0re** [comment]
Since now answer Issue Closed
