### ISSUE TITLE
plugin.video.tyl0re.tlc not working

### ISSUE THREAD

**Issue by synth00** [kodinerds/repo#166]
this is with v.2.0.6 when trying to open "All Shows" or something like that.

```
2020-04-20 22:54:24.457 T:2481767280   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: No JSON object could be decoded
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.tyl0re.tlc/default.py", line 23, in <module>
                                                from resources.lib import plugin
                                              File "/storage/.kodi/addons/plugin.video.tyl0re.tlc/resources/lib/plugin.py", line 531, in <module>
                                                listSeries(url, page, position, nosub)
                                              File "/storage/.kodi/addons/plugin.video.tyl0re.tlc/resources/lib/plugin.py", line 158, in listSeries
                                                DATA = json.loads(content)
                                              File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
                                              File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
                                              File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
                                            ValueError: No JSON object could be decoded
                                            -->End of Python script error report<--
2020-04-20 22:54:24.471 T:2473374576   ERROR: GetDirectory - Error getting plugin://plugin.video.tyl0re.tlc/?mode=listSeries&nosub=overview_all&origSERIE&page=1&position=0&url=https%3a%2f%2fwww.tlc.de%2fapi%2fsearch%3fquery%3d%2a%26limit%3d50
2020-04-20 22:54:24.493 T:3011986016   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.tyl0re.tlc/?mode=listSeries&nosub=overview_all&origSERIE&page=1&position=0&url=https%3a%2f%2fwww.tlc.de%2fapi%2fsearch%3fquery%3d%2a%26limit%3d50) failed
```

**Comment by Collabsvito** [comment]
Die passende Antwort dazu findest Du hier: [https://www.kodinerds.net/index.php/Thread/55451-L0REs-Blog-realvitos-Fixing-Thread/?postID=585804#post585804](url).

Schade aber lohnt sich nicht für eine Neuauflage. :weary:

Gruß
