### ISSUE TITLE
[plugin.video.euronews_com] PythonToCppException

### ISSUE THREAD

**Issue by iarspider** [kodinerds/repo#30]
```
15:09:52.953 T:4728   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode characters in position 1-5: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "\Kodi\addons\plugin.video.euronews_com\default.py", line 313, in <module>
                                                index()
                                              File "\Kodi\addons\plugin.video.euronews_com\default.py", line 288, in index
                                                Rubriken("http://"+language2+".euronews.com")
                                              File "\Kodi\addons\plugin.video.euronews_com\default.py", line 204, in Rubriken
                                                addDir(element.text.strip(), element["href"], 'Rubrik', "", "",text=str(anz))
                                              File "\Kodi\addons\plugin.video.euronews_com\default.py", line 171, in addDir
                                                u = sys.argv[0]+"?url="+urllib.quote_plus(url)+"&mode="+str(mode)+"&text="+str(text)+"&offset="+str(offset)+"&name"+str(name)
                                            UnicodeEncodeError: 'ascii' codec can't encode characters in position 1-5: ordinal not in range(128)
                                            -->End of Python script error report<--
```

**Comment by iarspider** [comment]
The addon is broken in many ways (e.g. it doesn't respect language setting for live video, always plays english). I will try to fix all this mess.

**Comment by tyl0re** [comment]
New Version of the Addon is online
